image: docker:24.0.7

services:
  - name: docker:24.0.7-dind
    command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: "containerregistry.xn--80aadjammc2a2e.tech"
  IMAGE_TAG: "$DOCKER_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA"
  IMAGE_LATEST: "$DOCKER_REGISTRY/$CI_PROJECT_PATH:latest"
  HEALTHCHECK_URL: "http://localhost:${SERVICE_PORT}/health"
  HEALTHCHECK_TIMEOUT: "60"
  IMAGE_ROLLBACK: "$DOCKER_REGISTRY/$CI_PROJECT_PATH:rollback"

stages:
  - build
  - test
  - deploy
  - healthcheck

# ────────────────────────────────────────────────────────────────────────
# СТЕЙДЖ 1: СБОРКА ОБРАЗА
# ────────────────────────────────────────────────────────────────────────
build:
  stage: build
  tags:
    - docker
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin "$DOCKER_REGISTRY"
  script:
    - echo "🏗️ Сборка образа $IMAGE_TAG"
    - docker build -t "$IMAGE_TAG" .
    - echo "📤 Пушим образ $IMAGE_TAG"
    - docker push "$IMAGE_TAG"
    - echo "🏷️  Тегируем как latest"
    - docker tag "$IMAGE_TAG" "$IMAGE_LATEST"
    - docker push "$IMAGE_LATEST"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always

# ────────────────────────────────────────────────────────────────────────
# СТЕЙДЖ 2: ТЕСТЫ
# ────────────────────────────────────────────────────────────────────────
dotnet-test-job:
  stage: test
  tags:
    - linux
    - deploy
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - echo "🧪 Запуск тестов..."
    - dotnet test --configuration Release --no-build --verbosity normal
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
  allow_failure: false

unit-test-job:
  stage: test
  tags:
    - linux
    - deploy
  script:
    - echo "Code coverage test is not allowed"

lint-test-job:
  stage: test
  tags:
    - linux
    - deploy
  script:
    - echo "No lint tests found."

# ────────────────────────────────────────────────────────────────────────
# СТЕЙДЖ 3: ДЕПЛОЙ
# ────────────────────────────────────────────────────────────────────────
deploy:
  stage: deploy
  tags:
    - linux
    - deploy
  script:
    - |
      echo "🚀 Деплой $SERVICE_NAME на $DEPLOY_HOST (HOST NETWORK MODE)"
      
      ssh -o StrictHostKeyChecking=yes -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST "
        echo '🔐 Авторизация в registry...'
        echo '$CI_REGISTRY_PASSWORD' | docker login -u '$CI_REGISTRY_USER' --password-stdin '$DOCKER_REGISTRY'
        
        echo '📥 Pull нового образа...'
        docker pull '$IMAGE_TAG'
        if docker ps -a --format '{{.Names}}' | grep -q \"^$CONTAINER_NAME\$\"; then
          CURRENT_IMAGE=\$(docker inspect --format='{{.Image}}' \"$CONTAINER_NAME\" 2>/dev/null)
          if [ -n \"\$CURRENT_IMAGE\" ]; then
            echo '🔖 Сохраняем текущий РАБОЧИЙ образ как $IMAGE_ROLLBACK для отката'
            docker tag \"\$CURRENT_IMAGE\" \"$IMAGE_ROLLBACK\"
          else
            echo '⚠️ Не удалось определить образ текущего контейнера'
          fi
        else
          echo 'ℹ️ Контейнер $CONTAINER_NAME не существует (первый деплой?)'
        fi
        
        echo '⏹️ Останавливаем старый контейнер...'
        docker stop '$CONTAINER_NAME' 2>/dev/null || true
        docker rm '$CONTAINER_NAME' 2>/dev/null || true
        
        echo '🚀 Запуск НОВОГО контейнера в HOST NETWORK MODE...'
        docker run -d \
          --name '$CONTAINER_NAME' \
          --network host \
          --restart unless-stopped \
          -e ASPNETCORE_ENVIRONMENT=Production \
          -e ASPNETCORE_URLS=http://*:$SERVICE_PORT \
          -e DB_HOST='$DB_HOST' \
          -e DB_PORT='$DB_PORT' \
          -e DB_USER='$DB_USER' \
          -e DB_PASSWORD='$DB_PASSWORD' \
          -e JWT_KEY='$JWT_KEY' \
          '$IMAGE_TAG'
        
        echo '✅ Контейнер запущен! Проверка:'
        sleep 3
        docker ps --filter name='$CONTAINER_NAME'
        ss -tulpn | grep ':$SERVICE_PORT' || echo '⏳ Порт ещё не слушается (старт приложения)...'
        docker logout '$DOCKER_REGISTRY'
      "
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success

# ────────────────────────────────────────────────────────────────────────
# СТЕЙДЖ 4: HEALTHCHECK
# ────────────────────────────────────────────────────────────────────────
healthcheck:
  stage: healthcheck
  tags:
    - linux
    - deploy
  script:
    - |
      echo "🩺 Проверка здоровья сервиса на порту $SERVICE_PORT..."
      START_TIME=$(date +%s)
      TIMEOUT=60
      while [ $(( $(date +%s) - START_TIME )) -lt $TIMEOUT ]; do
        if curl -sf --max-time 5 $HEALTHCHECK_URL > /dev/null; then
          echo "✅ Healthcheck успешен! Сервис отвечает на $HEALTHCHECK_URL"
          exit 0
        fi
        echo "⏳ Сервис ещё не готов, ждём 5 секунд..."
        sleep 5
      done
      echo "❌ Healthcheck провален сервис не ответил за $TIMEOUT секунд"
      exit 1
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
  allow_failure: true

# ────────────────────────────────────────────────────────────────────────
# ОТКАТ
# ────────────────────────────────────────────────────────────────────────
rollback:
  stage: deploy
  tags:
    - linux
    - deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $DEPLOY_PORT $DEPLOY_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - |
      echo "🔄 ОТКАТ $SERVICE_NAME на ПРЕДЫДУЩУЮ РАБОЧУЮ ВЕРСИЮ ($IMAGE_ROLLBACK)..."
      
      ssh -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST "
        if ! docker image inspect $IMAGE_ROLLBACK >/dev/null 2>&1; then
          echo '❌ КРИТИЧЕСКАЯ ОШИБКА Образ $IMAGE_ROLLBACK не найден!'
          echo 'Возможно, это первый деплой или образ был удалён.'
          echo 'Проверьте логи предыдущего деплоя — был ли сохранён образ?'
          exit 1
        fi
        
        echo '⏹️ Останавливаем текущий (сломанный) контейнер...'
        docker stop $CONTAINER_NAME 2>/dev/null || true
        docker rm $CONTAINER_NAME 2>/dev/null || true
        
        echo '🚀 Запускаем ПРЕДЫДУЩУЮ РАБОЧУЮ ВЕРСИЮ из $IMAGE_ROLLBACK...'
        docker run -d \
          --name $CONTAINER_NAME \
          --network host \
          --restart unless-stopped \
          -e ASPNETCORE_ENVIRONMENT=Production \
          -e ASPNETCORE_URLS=http://*:$SERVICE_PORT \
          -e DB_HOST='$DB_HOST' \
          -e DB_PORT='$DB_PORT' \
          -e DB_USER='$DB_USER' \
          -e DB_PASSWORD='$DB_PASSWORD' \
          -e JWT_KEY='$JWT_KEY' \
          $IMAGE_ROLLBACK
        
        echo '✅ Откат завершён! Проверка статуса:'
        sleep 3
        docker ps --filter name=$CONTAINER_NAME --format 'table {{.Names}}\t{{.Status}}'
        echo '🔍 Проверка порта:'
        ss -tulpn | grep ':$SERVICE_PORT' || echo '⚠️ Порт не слушается'
      "
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_failure
  when: manual
  allow_failure: true