// <auto-generated />
using ERP_Proflipper_WorkspaceService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERP_Proflipper_ProjectService.Migrations
{
    [DbContext(typeof(ProjectsDB))]
    [Migration("20251111143415_AddProjectResponsiblesTable")]
    partial class AddProjectResponsiblesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERP_Proflipper_ProjectService.Models.ProjectResponsibles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProjectId")
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleName")
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectResponsibles");
                });

            modelBuilder.Entity("ERP_Proflipper_ProjectService.Models.RolesLogins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuilderLogin")
                        .HasColumnType("text");

                    b.Property<string>("FinancierLogin")
                        .HasColumnType("text");

                    b.Property<string>("LawyerLogin")
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .HasColumnType("text");

                    b.Property<string>("ProjectManagerLogin")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("RolesLogins");
                });

            modelBuilder.Entity("ERP_Proflipper_ProjectService.Models.RolesRules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("boolean");

                    b.Property<string>("ProjectId")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("RolesRules");
                });

            modelBuilder.Entity("ERP_Proflipper_WorkspaceService.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("ApproveStatus")
                        .HasColumnType("integer");

                    b.Property<string>("BuilderCardJson")
                        .HasColumnType("text");

                    b.Property<string>("BuilderStatus")
                        .HasColumnType("text");

                    b.Property<string>("FinancierCardJson")
                        .HasColumnType("text");

                    b.Property<string>("FinancierStatus")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<string>("LawyerCardJson")
                        .HasColumnType("text");

                    b.Property<string>("LawyerStatus")
                        .HasColumnType("text");

                    b.Property<string>("NowStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PMCardJson")
                        .HasColumnType("text");

                    b.Property<string>("SellerCheckJson")
                        .HasColumnType("text");

                    b.Property<string>("SubStatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ERP_Proflipper_ProjectService.Models.ProjectResponsibles", b =>
                {
                    b.HasOne("ERP_Proflipper_WorkspaceService.Models.Project", "Project")
                        .WithMany("Responsibles")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ERP_Proflipper_ProjectService.Models.RolesLogins", b =>
                {
                    b.HasOne("ERP_Proflipper_WorkspaceService.Models.Project", "Project")
                        .WithOne("RolesLogins")
                        .HasForeignKey("ERP_Proflipper_ProjectService.Models.RolesLogins", "ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ERP_Proflipper_ProjectService.Models.RolesRules", b =>
                {
                    b.HasOne("ERP_Proflipper_WorkspaceService.Models.Project", "Project")
                        .WithMany("Rules")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ERP_Proflipper_WorkspaceService.Models.Project", b =>
                {
                    b.Navigation("Responsibles");

                    b.Navigation("RolesLogins");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
